/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: account
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const account_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    userId: String,
    type: String,
    provider: String,
    providerAccountId: String,
    refreshToken: String,
    accessToken: String,
    expiresAt: Number,
    tokenType: String,
    scope: String,
    idToken: String,
    sessionState: String,
  },
  { collection: 'account' }
);

export const Account = model('account_Mongoose', account_Mongoose);
