/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: authenticator
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const authenticator_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    credentialId: String,
    userId: String,
    providerAccountId: String,
    credentialPublicKey: String,
    counter: Number,
    credentialDeviceType: String,
    credentialBackedUp: Boolean,
    transports: String,
  },
  { collection: 'authenticator' }
);

export const Authenticator = model('authenticator_Mongoose', authenticator_Mongoose);
