/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: calendarEvent
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const calendarEvent_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    userId: String,
    folderId: String,
    title: String,
    description: String,
    location: String,
    startAt: Date,
    endAt: Date,
    isAllDay: Boolean,
    isPublic: Boolean,
    recurrence: String,
    metadata: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'calendarEvent' }
);

export const CalendarEvent = model('calendarEvent_Mongoose', calendarEvent_Mongoose);
