/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: calendarFolder
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const calendarFolder_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    userId: String,
    name: String,
    color: String,
    isDefault: Boolean,
    createdAt: Date,
    updatedAt: Date,
    visibility: String,
  },
  { collection: 'calendarFolder' }
);

export const CalendarFolder = model('calendarFolder_Mongoose', calendarFolder_Mongoose);
