/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: calendarEventParticipant
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const calendarEventParticipant_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    eventId: String,
    participantType: String,
    participantId: String,
    email: String,
    name: String,
    status: String,
    role: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'calendarEventParticipant' }
);

export const CalendarEventParticipant = model('calendarEventParticipant_Mongoose', calendarEventParticipant_Mongoose);
