/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: calendarEventShare
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const calendarEventShare_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    eventId: String,
    sharedWithUserId: String,
    permission: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'calendarEventShare' }
);

export const CalendarEventShare = model('calendarEventShare_Mongoose', calendarEventShare_Mongoose);
