/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: companyContact
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const companyContact_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    companyId: String,
    contactId: String,
    role: String,
    department: String,
    startDate: Date,
    endDate: Date,
    isActive: Boolean,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'companyContact' }
);

export const CompanyContact = model('companyContact_Mongoose', companyContact_Mongoose);
