/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: company
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const company_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    name: String,
    description: String,
    industry: String,
    size: String,
    website: String,
    address: String,
    city: String,
    state: String,
    country: String,
    postalCode: String,
    phone: String,
    email: String,
    status: String,
    metadata: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'company' }
);

export const Company = model('company_Mongoose', company_Mongoose);
