/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: companyCustomValue
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const companyCustomValue_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    companyId: String,
    fieldId: String,
    value: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'companyCustomValue' }
);

export const CompanyCustomValue = model('companyCustomValue_Mongoose', companyCustomValue_Mongoose);
