/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: contactCampaign
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const contactCampaign_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    contactId: String,
    campaignCode: String,
    joinedAt: Date,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'contactCampaign' }
);

export const ContactCampaign = model('contactCampaign_Mongoose', contactCampaign_Mongoose);
