/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: contact
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const contact_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    firstName: String,
    email: String,
    phone: String,
    address: String,
    createdAt: Date,
    updatedAt: Date,
    lastName: String,
    gender: String,
    company: String,
    jobTitle: String,
    city: String,
    state: String,
    country: String,
    postalCode: String,
    status: String,
    source: String,
    assignedTo: String,
    stripeCustomerId: String,
    name: String,
    priority: String,
    workExperience: String,
    currentRole: String,
    industry: String,
    skills: String,
    lastContactedAt: Date,
    remark: String,
    externalId: String,
    joinedAt: Date,
    nextFollowUpAt: Date,
    companyId: String,
  },
  { collection: 'contact' }
);

export const Contact = model('contact_Mongoose', contact_Mongoose);
