/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: contactActivity
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const contactActivity_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    contactId: String,
    userId: String,
    type: String,
    description: String,
    metadata: String,
    createdAt: Date,
    updatedAt: Date,
    initiatorType: String,
    initiatorId: String,
    subType: String,
  },
  { collection: 'contactActivity' }
);

export const ContactActivity = model('contactActivity_Mongoose', contactActivity_Mongoose);
