/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: contactCustomValue
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const contactCustomValue_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    contactId: String,
    fieldId: String,
    value: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'contactCustomValue' }
);

export const ContactCustomValue = model('contactCustomValue_Mongoose', contactCustomValue_Mongoose);
