/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: contactDeal
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const contactDeal_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    contactId: String,
    name: String,
    value: Number,
    status: String,
    expectedCloseDate: Date,
    actualCloseDate: Date,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'contactDeal' }
);

export const ContactDeal = model('contactDeal_Mongoose', contactDeal_Mongoose);
