/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: marketingCampaign
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const marketingCampaign_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    name: String,
    description: String,
    type: String,
    status: String,
    metrics: String,
    createdBy: String,
    updatedBy: String,
    createdAt: Date,
    updatedAt: Date,
    campaignCode: String,
  },
  { collection: 'marketingCampaign' }
);

export const MarketingCampaign = model('marketingCampaign_Mongoose', marketingCampaign_Mongoose);
