/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: paymentTrack
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const paymentTrack_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    contactId: String,
    userId: String,
    amount: Number,
    currency: String,
    status: String,
    stripePaymentId: String,
    linkClicked: Boolean,
    clickedAt: Date,
    paidAt: Date,
    expiresAt: Date,
    metadata: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'paymentTrack' }
);

export const PaymentTrack = model('paymentTrack_Mongoose', paymentTrack_Mongoose);
