/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: resourceContentShare
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const resourceContentShare_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    resourceId: String,
    sharedWithUserId: String,
    permission: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'resourceContentShare' }
);

export const ResourceContentShare = model('resourceContentShare_Mongoose', resourceContentShare_Mongoose);
