/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: resourceContent
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const resourceContent_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    title: String,
    description: String,
    content: String,
    tags: String,
    visibility: String,
    createdBy: String,
    updatedBy: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'resourceContent' }
);

export const ResourceContent = model('resourceContent_Mongoose', resourceContent_Mongoose);
