/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: resourceEmails
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const resourceEmails_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    title: String,
    description: String,
    subject: String,
    content: String,
    tags: String,
    visibility: String,
    createdBy: String,
    updatedBy: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'resourceEmails' }
);

export const ResourceEmails = model('resourceEmails_Mongoose', resourceEmails_Mongoose);
