/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: resourceContentSendTrack
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const resourceContentSendTrack_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    resourceId: String,
    contactId: String,
    sentAt: Date,
    sentBy: String,
    status: String,
    metadata: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'resourceContentSendTrack' }
);

export const ResourceContentSendTrack = model('resourceContentSendTrack_Mongoose', resourceContentSendTrack_Mongoose);
