/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: session
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const session_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    sessionToken: String,
    userId: String,
    expires: Date,
  },
  { collection: 'session' }
);

export const Session = model('session_Mongoose', session_Mongoose);
