/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: siteConfig
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const siteConfig_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    key: String,
    value: String,
    description: String,
    type: String,
    isPublic: Boolean,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'siteConfig' }
);

export const SiteConfig = model('siteConfig_Mongoose', siteConfig_Mongoose);
