/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: subscriptionCoupon
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const subscriptionCoupon_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    code: String,
    discountPercent: Number,
    maxUses: Number,
    usedCount: Number,
    expiresAt: Date,
    createdBy: String,
    createdAt: Date,
    updatedAt: Date,
    isActive: Boolean,
    company: String,
    planId: String,
    stripeId: String,
    source: String,
  },
  { collection: 'subscriptionCoupon' }
);

export const SubscriptionCoupon = model('subscriptionCoupon_Mongoose', subscriptionCoupon_Mongoose);
