/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: teamContact
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const teamContact_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    teamId: String,
    contactId: String,
    assignedTo: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'teamContact' }
);

export const TeamContact = model('teamContact_Mongoose', teamContact_Mongoose);
