/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: teamMeeting
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const teamMeeting_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    teamId: String,
    title: String,
    description: String,
    meetingDate: Date,
    status: String,
    createdBy: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'teamMeeting' }
);

export const TeamMeeting = model('teamMeeting_Mongoose', teamMeeting_Mongoose);
