/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: team
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const team_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    name: String,
    description: String,
    createdBy: String,
    createdAt: Date,
    updatedAt: Date,
    leaderId: String,
    subLeaderId: String,
    referralId: String,
    campaignCode: String,
    remarks: String,
    companyId: String,
  },
  { collection: 'team' }
);

export const Team = model('team_Mongoose', team_Mongoose);
