/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: teamActivity
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const teamActivity_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    teamId: String,
    userId: String,
    type: String,
    initiatorType: String,
    initiatorId: String,
    subType: String,
    description: String,
    metadata: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'teamActivity' }
);

export const TeamActivity = model('teamActivity_Mongoose', teamActivity_Mongoose);
