/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: teamCustomField
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const teamCustomField_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    name: String,
    label: String,
    type: String,
    options: String,
    required: Boolean,
    defaultValue: String,
    description: String,
    isActive: Boolean,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'teamCustomField' }
);

export const TeamCustomField = model('teamCustomField_Mongoose', teamCustomField_Mongoose);
