/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: teamCustomValue
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const teamCustomValue_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    teamId: String,
    fieldId: String,
    value: String,
    createdAt: Date,
    updatedAt: Date,
  },
  { collection: 'teamCustomValue' }
);

export const TeamCustomValue = model('teamCustomValue_Mongoose', teamCustomValue_Mongoose);
