/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: user
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const user_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    name: String,
    email: String,
    emailVerified: Date,
    image: String,
    password: String,
    firstName: String,
    lastName: String,
    role: String,
    username: String,
  },
  { collection: 'user' }
);

export const User = model('user_Mongoose', user_Mongoose);
