/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: userNotifications
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const userNotifications_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: Number,
    userId: String,
    type: String,
    title: String,
    message: String,
    read: Boolean,
    createdAt: Date,
    updatedAt: Date,
    metadata: String,
  },
  { collection: 'userNotifications' }
);

export const UserNotifications = model('userNotifications_Mongoose', userNotifications_Mongoose);
