/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: userTask
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const userTask_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    id: String,
    userId: String,
    title: String,
    description: String,
    status: String,
    priority: String,
    dueDate: Date,
    completedAt: Date,
    assignedTo: String,
    labels: String,
    attachments: String,
    parentTaskId: String,
    metadata: String,
    createdAt: Date,
    updatedAt: Date,
    content: String,
  },
  { collection: 'userTask' }
);

export const UserTask = model('userTask_Mongoose', userTask_Mongoose);
