/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: verificationToken
 * Language: JavaScript
 * Template: Mongoose
 * Generated on 2025-02-10
 */
import mongoose from 'mongoose';

const Schema = mongoose.Schema;
const model = mongoose.model;

export const verificationToken_Mongoose = new Schema(
  {
    _id: mongoose.ObjectId,
    identifier: String,
    token: String,
    expires: Date,
  },
  { collection: 'verificationToken' }
);

export const VerificationToken = model('verificationToken_Mongoose', verificationToken_Mongoose);
